### ISSUE TITLE
应用绑定自定义域名报错

### ISSUE THREAD

**Issue by zhouyq** [goodrain/rainbond#11]
第一次点击 会有报错，但再点击一次会成功，实际openresty已经注册该域名

日志：
```bash
2017-12-16 21:46:35 [ERROR] manage03 [post] /app/ui/www/views/ajax/service_actions.py:1209 {"url": "http://region.goodrain.me:8888/v2/tenants/zggk/services/gr2241a2/domains", "body": {"raw": "404 page not found\n"}, "httpcode": 404, "method": "POST", "apitype": "Not specified"}
Traceback (most recent call last):
File "/app/ui/www/views/ajax/service_actions.py", line 1176, in post
region_api.bindDomain(self.service.service_region, self.tenantName, self.serviceAlias, data)
File "/app/ui/www/apiclient/regionapi.py", line 722, in bindDomain
res, body = self._post(url, self.default_headers, json.dumps(body), region=region)
File "/app/ui/www/apiclient/baseclient.py", line 107, in _post
res, body = self._check_status(url, 'POST', response, content)
File "/app/ui/www/apiclient/baseclient.py", line 53, in _check_status
raise self.CallApiError(self.apitype, url, method, res, body)
CallApiError: {"url": "http://region.goodrain.me:8888/v2/tenants/zggk/services/gr2241a2/domains", "body": {"raw": "404 page not found\n"}, "httpcode": 404, "method": "POST", "apitype": "Not specified"}
```

截图
![image](https://user-images.githubusercontent.com/1088647/34087989-91b3e72e-e3e1-11e7-9bc8-590b092e5b21.png)

![image](https://user-images.githubusercontent.com/1088647/34087997-9b219720-e3e1-11e7-8f76-ceaa0fd0c8b6.png)

**Comment by barnettZQG** [comment]
统一后端服务注册逻辑，杜绝服务注册数据冗余。
