### ISSUE TITLE
新增管理节点报错

### ISSUE THREAD

**Issue by alex1528** [goodrain/rainbond#15]
```
Dec 19 22:35:55 m02 start-node.sh[3400]: Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Dec 19 22:36:06 m02 start-node.sh[3400]: time="2017-12-19T22:36:06+08:00" level=error msg="create discover manager error.dial tcp: address 172.16.2.2
Dec 19 22:36:06 m02 start-node.sh[3400]: time="2017-12-19T22:36:06+08:00" level=info msg="start a event log handle core. connect server 127.0.0.1:636
Dec 19 22:36:06 m02 start-node.sh[3400]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 19 22:36:06 m02 start-node.sh[3400]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12a338d]
Dec 19 22:36:06 m02 start-node.sh[3400]: goroutine 1 [running]:
Dec 19 22:36:06 m02 start-node.sh[3400]: github.com/goodrain/rainbond/pkg/event.(*manager).Start(0xc4201f3c20, 0x0, 0x0)
Dec 19 22:36:06 m02 start-node.sh[3400]: /go/src/github.com/goodrain/rainbond/pkg/event/manager.go:122 +0x32d
Dec 19 22:36:06 m02 start-node.sh[3400]: github.com/goodrain/rainbond/pkg/event.NewManager(0xc4203d2290, 0x1, 0x1, 0xc4203d2400, 0x1, 0x1, 0x0, 0x0)
Dec 19 22:36:06 m02 start-node.sh[3400]: /go/src/github.com/goodrain/rainbond/pkg/event/manager.go:95 +0x332
Dec 19 22:36:06 m02 start-node.sh[3400]: github.com/goodrain/rainbond/cmd/node/server.Run(0xc420273600, 0x0, 0x0)
Dec 19 22:36:06 m02 start-node.sh[3400]: /go/src/github.com/goodrain/rainbond/cmd/node/server/server.go:46 +0x117
Dec 19 22:36:06 m02 start-node.sh[3400]: main.main()
Dec 19 22:36:06 m02 start-node.sh[3400]: /go/src/github.com/goodrain/rainbond/cmd/node/node.go:31 +0x36
Dec 19 22:36:06 m02 systemd[1]: rainbond-node.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 19 22:36:06 m02 systemd[1]: Unit rainbond-node.service entered failed state.
Dec 19 22:36:06 m02 systemd[1]: rainbond-node.service failed.
Dec 19 22:36:16 m02 systemd[1]: rainbond-node.service holdoff time over, scheduling restart.
Dec 19 22:36:16 m02 systemd[1]: Started goodrain rainbond-node.
```

**Comment by ysicing** [comment]
发现部分服务扩容存在问题，新增管理节点这部分还在调整

**Comment by ysicing** [comment]
release 3.4.1 已经解决安装管理节点问题
