### ISSUE TITLE
pipeline create project : Invalid url given

### ISSUE THREAD

**Issue by xjk27400861** [goodrain/rainbond#1582]
安装好了gitlab，gitlab-runner，pipeline插件；添加应用服务报错：Invalid url given
仓库验证能够成功，但是添加应用报错，无效的连接
相关错误信息：
2023-03-11 17:21:06.504 ERROR 1 --- [io-9090-exec-10] c.d.p.c.e.GlobalExceptionHandler : 统一异常拦截 -> uri= POST: /app-service/add params={}
1783
1784
com.devops.plugins.common.exception.BusinessRuntimeException: Invalid url given
1785
at com.devops.plugins.gitlab.service.impl.HookServiceImpl.createProjectHook(HookServiceImpl.java:50) ~[plugins-gitlab-1.0-SNAPSHOT.jar!/:na]
1786
at com.devops.plugins.core.service.impl.AppServiceServiceImpl.createWebhook(AppServiceServiceImpl.java:1034) ~[classes!/:na]
1787
at com.devops.plugins.core.service.impl.AppServiceServiceImpl.handleExternalGitlab(AppServiceServiceImpl.java:923) ~[classes!/:na]
1788
at com.devops.plugins.core.service.impl.AppServiceServiceImpl.create(AppServiceServiceImpl.java:404) ~[classes!/:na]
1789
at com.devops.plugins.core.service.impl.AppServiceServiceImpl$$FastClassBySpringCGLIB$$48a127e9.invoke(<generated>) ~[classes!/:na]
1790
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar!/:5.3.20]
1791
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar!/:5.3.20]
1792
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar!/:5.3.20]
1793
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
1794
at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.9.jar!/:5.3.9]
1795
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.9.jar!/:5.3.9]
1796
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.9.jar!/:5.3.9]
1797
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.20.jar!/:5.3.20]
1798
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar!/:5.3.20]
1799
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.20.jar!/:5.3.20]
1800
at com.devops.plugins.core.service.impl.AppServiceServiceImpl$$EnhancerBySpringCGLIB$$d34f0b99.create(<generated>) ~[classes!/:na]
1801
at com.devops.plugins.core.controller.AppServiceController.create(AppServiceController.java:87) ~[classes!/:na]
1802
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232-heroku]
1803
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232-heroku]
1804
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232-heroku]
1805
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232-heroku]
1806
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.20.jar!/:5.3.20]
1807
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.20.jar!/:5.3.20]
1808
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1809
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1810
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1811
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1812
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1813
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1814
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1815
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1816
at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat-embed-core-9.0.63.jar!/:4.0.3]
1817
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.20.jar!/:5.3.20]
1818
at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.63.jar!/:4.0.3]
1819
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.63.jar!/:na]
1820
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.63.jar!/:na]
1821
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.63.jar!/:na]
1822
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.63.jar!/:na]
1823
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.63.jar!/:na]
1824
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.20.jar!/:5.3.20]
1825
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.20.jar!/:5.3.20]
1826
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.63.jar!/:na]
1827
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.63.jar!/:na]
1828
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.20.jar!/:5.3.20]
1829
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.20.jar!/:5.3.20]
1830
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.63.jar!/:na]
1831
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.63.jar!/:na]
1832
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.20.jar!/:5.3.20]
1833
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.20.jar!/:5.3.20]
1834
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.63.jar!/:na]
1835
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.63.jar!/:na]
1836
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.63.jar!/:na]
1837
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.63.jar!/:na]
1838
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.63.jar!/:na]
1839
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.63.jar!/:na]
1840
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.63.jar!/:na]
1841
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.63.jar!/:na]
1842
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769) [tomcat-embed-core-9.0.63.jar!/:na]
1843
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat-embed-core-9.0.63.jar!/:na]
1844
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-embed-core-9.0.63.jar!/:na]
1845
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.63.jar!/:na]
1846
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) [tomcat-embed-core-9.0.63.jar!/:na]
1847
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.63.jar!/:na]
1848
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.63.jar!/:na]
1849
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.63.jar!/:na]
1850
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.63.jar!/:na]
1851
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.63.jar!/:na]
1852
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_232-heroku]
1853
Caused by: org.gitlab4j.api.GitLabApiException: Invalid url given
1854
at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633) ~[gitlab4j-api-4.19.0.jar!/:na]
1855
at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:286) ~[gitlab4j-api-4.19.0.jar!/:na]
1856
at org.gitlab4j.api.ProjectApi.addHook(ProjectApi.java:2085) ~[gitlab4j-api-4.19.0.jar!/:na]
1857
at com.devops.plugins.gitlab.service.impl.HookServiceImpl.createProjectHook(HookServiceImpl.java:48) ~[plugins-gitlab-1.0-SNAPSHOT.jar!/:na]
1858
... 67 common frames omitted

**Comment by zzzhangqi** [comment]
无法复现该问题，全新安装 Rainbond、GitLab、GitLab runner、pipeline 测试创建应用没问题，可以检查下 `pipeline-backend` 配置。

我将该问题关闭，如有问题请再次打开

**Comment by zzzhangqi** [comment]
无法复现该问题，全新安装 Rainbond、GitLab、GitLab runner、pipeline 测试创建应用没问题，可以检查下 `pipeline-backend` 配置。

我将该问题关闭，如有问题请再次打开

**Comment by massinger** [comment]
需要在gitlab中配置允许webhook从本地网络访问
