### ISSUE TITLE
node启动有报错

### ISSUE THREAD

**Issue by mikojia** [goodrain/rainbond#159]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ ] Rainbond versions(Rainbond node 3.7.2-8ee65120-2018-11-12-15)

```
Nov 12 16:00:42 manage01 start-node.sh[13963]: ERROR: logging before flag.Parse: E1112 16:00:42.048714   13963 reflector.go:201] github.com/goodrain/rainbond/vendor/k8s.io/client-go/infor
Nov 12 16:00:42 manage01 start-node.sh[13963]: time="2018-11-12T16:00:42+08:00" level=error msg="Can not get endpoints of the key /rainbond/endpoint/HOSTNAME"
Nov 12 16:00:42 manage01 start-node.sh[13963]: time="2018-11-12T16:00:42+08:00" level=warning msg="Failed to inject endpoints of key HOSTNAME"
Nov 12 16:00:43 manage01 start-node.sh[13963]: ERROR: logging before flag.Parse: E1112 16:00:43.044467   13963 reflector.go:201] github.com/goodrain/rainbond/vendor/k8s.io/client-go/infor
Nov 12 16:00:43 manage01 start-node.sh[13963]: ERROR: logging before flag.Parse: E1112 16:00:43.045951   13963 reflector.go:201] github.com/goodrain/rainbond/vendor/k8s.io/client-go/infor
Nov 12 16:00:54 manage01 start-node.sh[13963]: ERROR: logging before flag.Parse: E1112 16:00:54.091103   13963 reflector.go:201] github.com/goodrain/rainbond/vendor/k8s.io/client-go/infor
Nov 12 16:01:13 manage01 start-node.sh[13963]: fatal error: concurrent map read and map write
Nov 12 16:01:13 manage01 start-node.sh[13963]: goroutine 785 [running]:
Nov 12 16:01:13 manage01 start-node.sh[13963]: runtime.throw(0x1bcd315, 0x21)
Nov 12 16:01:13 manage01 start-node.sh[13963]: /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0008cf518 sp=0xc0008cf4e8 pc=0x42e242
Nov 12 16:01:13 manage01 start-node.sh[13963]: runtime.mapaccess2_faststr(0x190cda0, 0xc000774840, 0xc00063f5b0, 0xa, 0x43f7ae, 0xc0008cf758)
Nov 12 16:01:13 manage01 start-node.sh[13963]: /usr/local/go/src/runtime/map_faststr.go:110 +0x458 fp=0xc0008cf588 sp=0xc0008cf518 pc=0x4143b8
Nov 12 16:01:13 manage01 start-node.sh[13963]: github.com/goodrain/rainbond/node/nodem/healthy.(*probeManager).EnableWatcher(0xc000210070, 0xc00063f5b0, 0xa, 0xc0000ab700, 0x20)
Nov 12 16:01:13 manage01 start-node.sh[13963]: /go/src/github.com/goodrain/rainbond/node/nodem/healthy/health_manager.go:237 +0xf0 fp=0xc0008cf628 sp=0xc0008cf588 pc=0x16bce70
Nov 12 16:01:13 manage01 start-node.sh[13963]: github.com/goodrain/rainbond/node/nodem/controller.(*ManagerService).StartSyncService.func1(0xc0001e0a20, 0x1dbaac0, 0xc000191e00)
Nov 12 16:01:13 manage01 start-node.sh[13963]: /go/src/github.com/goodrain/rainbond/node/nodem/controller/manager_service.go:147 +0xbc fp=0xc0008cf7c8 sp=0xc0008cf628 pc=0x16c1acc
Nov 12 16:01:13 manage01 start-node.sh[13963]: runtime.goexit()
Nov 12 16:01:13 manage01 start-node.sh[13963]: /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0008cf7d0 sp=0xc0008cf7c8 pc=0x45e3b1
```

**Comment by barnettZQG** [comment]
closed
