### ISSUE TITLE
将应用发布到本地商店提示数据分享错误。

### ISSUE THREAD

**Issue by SkadiArk** [goodrain/rainbond#1963]
对应用的组件进行构建，完成后再将组件发布到本地商店时页面右上角会提示数据中心分享错误，在控制台显示接口请求失败，状态500。检查rainbond的pod都是正常运行，挂载的文件系统剩余空间也足够。

日志显示为：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/ui/console/services/share_services.py", line 500, in sync_event
    res, re_body = region_api.share_service(region_name, tenant_name, record_event.service_alias, body)
  File "/app/ui/www/apiclient/regionapi.py", line 832, in share_service
    res, body = self._post(url, self.default_headers, region=region, body=json.dumps(body))
  File "/app/ui/www/apiclient/regionapibaseclient.py", line 255, in _post
    response, content = self._request(url, 'POST', headers=headers, body=body, *args, **kwargs)
  File "/app/ui/www/apiclient/regionapibaseclient.py", line 179, in _request
    raise ServiceHandleException(error_code=10411, msg="Exception", msg_show="访问数据中心异常，请稍后重试")
console.exception.main.ServiceHandleException: (400, 10411, 'Exception', '访问数据中心异常，请稍后重试')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/ui/console/services/share_services.py", line 527, in sync_event
    raise ServiceHandleException(msg="share failed", msg_show="数据中心分享错误", status_code=500)
console.exception.main.ServiceHandleException: (500, None, 'share failed', '数据中心分享错误')

<img width="1207" alt="微信图片_20240817155202" src="https://github.com/user-attachments/assets/05760e66-2728-44c9-93ac-d812aeb2c36c">

**Comment by ZhangSetSail** [comment]
提供一下 api 和 chaos 日志

**Comment by SkadiArk** [comment]
<img width="1280" alt="d49d6634c7493457765af79cc6c4272" src="https://github.com/user-attachments/assets/26dec25f-1994-40c1-8313-4849b3d9e24c">
这个是chaos的日志，我在16：28进行的发布操作

**Comment by SkadiArk** [comment]
api的日志
<img width="1280" alt="f441feade322eae7ad9e6d9c664ec87" src="https://github.com/user-attachments/assets/8aa4e554-8d6d-4839-a254-466db3491a7d">
<img width="1280" alt="59c6758e9538a1a977e443edfc187c3" src="https://github.com/user-attachments/assets/29235fc9-7b25-4e32-90fc-b4734126011e">

**Comment by SkadiArk** [comment]
api日志没有显示异常

**Comment by ZhangSetSail** [comment]
什么版本

**Comment by SkadiArk** [comment]
enterprise-2110

**Comment by ZhangSetSail** [comment]
企业版咱们直接找运维同事协助吧

**Comment by ZhangSetSail** [comment]
企业版的话找专人支持解决。
