### ISSUE TITLE
5.1.8外置数据库升级到5.1.9异常 UI打不开。

### ISSUE THREAD

**Issue by yszansx** [goodrain/rainbond#585]
【BUG描述】
私有化高可用安装云帮5.1.8集群使用外置数据库，按文档升级到5.1.9后UI打不开，已经按文档完成升级后的验证。外置数据库版本5.6.46
安装时报错提示信息
Error：NO such container ：rbd-db

UI报错日志如下
OperationalError: (1054, "Unknown column 'tenant_service.oauth_service_id' in 'field list'")
2019-12-13 17:19:32 [ERROR] localhost [get] /app/ui/console/views/services_toplogical.py:114 (1054, "Unknown column 'tenant_service.oauth_service_id' in 'field list'")
Traceback (most recent call last):
  File "/app/ui/console/views/services_toplogical.py", line 110, in get
    enterprise_id=self.team.enterprise_id)
  File "/app/ui/console/services/topological_services.py", line 24, in get_group_topological_graph
    service_map = {x.service_id: x for x in service_list}
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception

而且数据库里面找不到相应的tenant_service.oauth_service_id字段。

【部署环境】
- Rainbond版本(执行`grctl version`获取):Rainbond grctl v5.1.9-release-32cc2ba-2019-12-13-05
- 操作系统类型和版本:Ubuntu 16.04
- 离线部署/网络开放：vip

**Comment by barnettZQG** [comment]
@yszansx 
进入平台数据库重新执行升级SQL. 
```
use console;
```
https://github.com/goodrain/rainbond-console/blob/V5.1/sql/5.1.8-5.1.9.sql

**Comment by yszansx** [comment]
按上述处理方法已经解决。或者按最新的更新文档也是可以通过。
