### ISSUE TITLE
团队的默认集群删除不同步

### ISSUE THREAD

**Issue by kitsudog** [goodrain/rainbond#932]
一个团队拥有多个集群的时候
企业视图下团队是去默认集群(第一个集群)的环境的
但是如果删除了这个集群的权限
会导致企业视图下的该团队入口会有异常
![image](https://user-images.githubusercontent.com/1467143/113256673-18c66080-92fc-11eb-8e96-f6723d8a003c.png)

`
2021-04-01 15:08:11 [ERROR] localhost [__get_tenant_region_info] /app/ui/www/apiclient/regionapi.py:54 tenant x4d15b7o is not init in region laifa-main
2021-04-01 15:08:11 [ERROR] localhost [get] /app/ui/console/views/protocols.py:48 
Traceback (most recent call last):
  File "/app/ui/console/views/protocols.py", line 41, in get
    protocols_info = region_api.get_protocols(region_name, self.team.tenant_name)
  File "/app/ui/www/apiclient/regionapi.py", line 1167, in get_protocols
    tenant_region = self.__get_tenant_region_info(tenant_name, region)
  File "/app/ui/www/apiclient/regionapi.py", line 55, in __get_tenant_region_info
    raise http.Http404
django.http.response.Http404
2021-04-01 15:08:11 [ERROR] localhost [custom_exception_handler] /app/ui/console/views/base.py:470 'Http404' object has no attribute 'message'
Traceback (most recent call last):
  File "/app/ui/console/views/protocols.py", line 41, in get
    protocols_info = region_api.get_protocols(region_name, self.team.tenant_name)
  File "/app/ui/www/apiclient/regionapi.py", line 1167, in get_protocols
    tenant_region = self.__get_tenant_region_info(tenant_name, region)
  File "/app/ui/www/apiclient/regionapi.py", line 55, in __get_tenant_region_info
    raise http.Http404
django.http.response.Http404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/ui/console/views/protocols.py", line 49, in get
    result = general_message(200, e.message, "查询成功", list=["http", "stream"])
AttributeError: 'Http404' object has no attribute 'message'
2021-04-01 15:08:11 [ERROR] localhost [__get_tenant_region_info] /app/ui/www/apiclient/regionapi.py:54 tenant x4d15b7o is not init in region laifa-main
2021-04-01 15:08:11 [ERROR] localhost [get] /app/ui/console/views/protocols.py:48 
Traceback (most recent call last):
  File "/app/ui/console/views/protocols.py", line 41, in get
    protocols_info = region_api.get_protocols(region_name, self.team.tenant_name)
  File "/app/ui/www/apiclient/regionapi.py", line 1167, in get_protocols
    tenant_region = self.__get_tenant_region_info(tenant_name, region)
  File "/app/ui/www/apiclient/regionapi.py", line 55, in __get_tenant_region_info
    raise http.Http404
django.http.response.Http404
2021-04-01 15:08:11 [ERROR] localhost [custom_exception_handler] /app/ui/console/views/base.py:470 'Http404' object has no attribute 'message'
Traceback (most recent call last):
  File "/app/ui/console/views/protocols.py", line 41, in get
    protocols_info = region_api.get_protocols(region_name, self.team.tenant_name)
  File "/app/ui/www/apiclient/regionapi.py", line 1167, in get_protocols
    tenant_region = self.__get_tenant_region_info(tenant_name, region)
  File "/app/ui/www/apiclient/regionapi.py", line 55, in __get_tenant_region_info
    raise http.Http404
django.http.response.Http404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/ui/console/views/protocols.py", line 49, in get
    result = general_message(200, e.message, "查询成功", list=["http", "stream"])
AttributeError: 'Http404' object has no attribute 'message'
`

**Comment by barnettZQG** [comment]
release in 5.3.1
